// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_a0zYM-q8E4UlxcYl_mgETDTbf0coFdw',
    appId: '1:295622193776:web:ee776d9ec6254bf2993ab5',
    messagingSenderId: '295622193776',
    projectId: 'social-app-8905b',
    authDomain: 'social-app-8905b.firebaseapp.com',
    storageBucket: 'social-app-8905b.firebasestorage.app',
    measurementId: 'G-7HCFJTTCLJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWS48Ruqh5kiLNCJIV0P6xjX8Y2oFsMZU',
    appId: '1:295622193776:android:a0c9945bd5d8b8fe993ab5',
    messagingSenderId: '295622193776',
    projectId: 'social-app-8905b',
    storageBucket: 'social-app-8905b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSfPWyRJY2ZDwAj_yd17logVqjR4Y7a1U',
    appId: '1:295622193776:ios:02f16e7c64a851df993ab5',
    messagingSenderId: '295622193776',
    projectId: 'social-app-8905b',
    storageBucket: 'social-app-8905b.firebasestorage.app',
    iosBundleId: 'com.example.testFlutterApp',
  );
}
